version: '3.8'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aqa_shop
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: aqa_shop
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  gate-simulator:
    image: node:latest
    working_dir: /usr/src/app
    volumes:
      - ./gate-simulator:/usr/src/app
    command: npm install && npm start
    ports:
      - "9999:9999"

volumes:
  mysql-data:
  postgres-data:
